"""Ledger connections. PostgreSQL production; SQLite fixtures and import source.

The narrow SQL compatibility boundary preserves the established ledger queries
while migrating their storage. Native Viber databases never use this adapter.
"""
from contextlib import closing
import atexit
import hashlib
import os
from pathlib import Path
import re
import sqlite3
import threading

_pools = {}
_lock = threading.RLock()
_test_schemas = set()


@atexit.register
def close_pools():
    for pool in _pools.values():
        pool.close(timeout=2)


def postgres(target):
    return str(target).startswith(('postgresql://', 'postgres://'))


def _parts(sql, separator):
    parts, part, quote = [], [], None
    i = 0
    while i < len(sql):
        c = sql[i]
        if quote:
            part.append(c)
            if c == quote:
                if i + 1 < len(sql) and sql[i + 1] == quote:
                    part.append(sql[i + 1]); i += 1
                else:
                    quote = None
        elif c in ("'", '"'):
            quote = c; part.append(c)
        elif c == separator:
            parts.append(''.join(part)); part = []
        else:
            part.append(c)
        i += 1
    parts.append(''.join(part))
    return parts


class Row:
    def __init__(self, names, values, hide_rowid=False):
        self.names, self.values = names, tuple(values)
        self.hide = hide_rowid

    def keys(self):
        return [n for n in self.names if not (self.hide and n == 'rowid')]

    def __getitem__(self, key):
        return self.values[key] if isinstance(key, (int, slice)) else self.values[self.names.index(key)]

    def __iter__(self):
        return iter(self.values)

    def __len__(self):
        return len(self.values)


class Cursor:
    def __init__(self, rows=(), rowcount=0, lastrowid=None):
        self.rows = list(rows)
        self.rowcount, self.lastrowid = rowcount, lastrowid
        self.position = 0

    def fetchone(self):
        if self.position >= len(self.rows):
            return None
        value = self.rows[self.position]; self.position += 1
        return value

    def fetchall(self):
        result = self.rows[self.position:]; self.position = len(self.rows)
        return result

    def __iter__(self):
        return iter(self.fetchall())


class PostgresConnection:
    dialect = 'postgresql'

    def __init__(self, target, schema='public'):
        from psycopg_pool import ConnectionPool
        self.target, self.schema = target, schema
        key = target
        with _lock:
            if key not in _pools:
                _pools[key] = ConnectionPool(target, min_size=1, max_size=16,
                    kwargs={'autocommit': False}, open=True)
            self.pool = _pools[key]
        self.raw = self.pool.getconn(timeout=20)
        self.raw.execute('SET search_path TO ' + schema + ',public')
        self.closed = False

    def __enter__(self):
        return self

    def __exit__(self, kind, value, traceback):
        self.rollback() if kind else self.commit()

    def columns(self, table):
        return [r[0] for r in self.raw.execute(
            'SELECT column_name FROM information_schema.columns WHERE table_schema=%s AND table_name=%s '
            'AND column_name!=\'rowid\' ORDER BY ordinal_position', (self.schema, table)).fetchall()]

    def execute(self, sql, params=()):
        sql = sql.strip().rstrip(';')
        if sql.upper() in ('BEGIN', 'BEGIN IMMEDIATE'):
            if sql.upper().endswith('IMMEDIATE'):
                self.raw.execute("SELECT pg_advisory_xact_lock(hashtext(current_schema() || ':ledger-claim'))")
            return Cursor()
        match = re.fullmatch(r'PRAGMA table_info\((\w+)\)', sql, re.I)
        if match:
            return Cursor([Row(['cid','name','type','notnull','dflt_value','pk'],
                              [i,n,'',0,None,0]) for i,n in enumerate(self.columns(match[1]))])
        if 'sqlite_master' in sql:
            sql = sql.replace("sqlite_master", "information_schema.tables").replace("type='table' AND name=", 'table_schema=current_schema() AND table_name=')
        sql = re.sub(r'\bDATETIME\b', 'TEXT', sql, flags=re.I)
        sql = re.sub(r'\bINTEGER PRIMARY KEY AUTOINCREMENT\b', 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', sql, flags=re.I)
        sql = re.sub(r'\bINTEGER\b', 'BIGINT', sql, flags=re.I)
        if re.match(r'CREATE TABLE', sql, re.I):
            end = sql.rfind(')')
            sql = sql[:end] + ', rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE' + sql[end:]
        ignore = bool(re.match('INSERT OR IGNORE', sql, re.I))
        replace = re.match(r'INSERT OR REPLACE INTO (\w+) VALUES', sql, re.I)
        sql = re.sub('INSERT OR (?:IGNORE|REPLACE)', 'INSERT', sql, flags=re.I)
        if replace:
            table = replace[1]
            cols = self.columns(table)
            sql = sql.replace('INTO ' + table + ' VALUES', 'INTO ' + table + '(' + ','.join(cols) + ') VALUES')
            sql += ' ON CONFLICT (' + cols[0] + ') DO UPDATE SET ' + ','.join(c+'=excluded.'+c for c in cols[1:])
        if ignore:
            sql += ' ON CONFLICT DO NOTHING'
        sql = re.sub(r'\bMAX\((\?,\s*c\.reply_since_rowid)\)', r'GREATEST(\1)', sql, flags=re.I)
        sql = '%s'.join(_parts(sql.replace('%', '%%'), '?')) if params else sql
        lead_insert = bool(re.match(r'INSERT INTO leads\b', sql, re.I)) and 'RETURNING' not in sql.upper()
        if lead_insert:
            sql += ' RETURNING id'
        cur = self.raw.execute(sql, params or None)
        rows = []
        lastrowid = None
        if cur.description:
            names = [c.name for c in cur.description]
            hide = bool(re.search(r'SELECT\s+(?:\w+\.)?\*', sql, re.I))
            rows = [Row(names, row, hide) for row in cur.fetchall()]
            if lead_insert and rows:
                lastrowid = rows[0][0]
        return Cursor(rows, cur.rowcount, lastrowid)

    def executemany(self, sql, rows):
        for row in rows:
            self.execute(sql, row)

    def executescript(self, sql):
        for statement in _parts(sql, ';'):
            if statement.strip():
                self.execute(statement)

    def commit(self):
        self.raw.commit()

    def rollback(self):
        self.raw.rollback()

    def close(self):
        if not self.closed:
            self.raw.rollback()
            self.pool.putconn(self.raw)
            self.closed = True


def bootstrap(target, schema='public'):
    import psycopg
    with psycopg.connect(target, autocommit=True) as db:
        db.execute('CREATE SCHEMA IF NOT EXISTS ' + schema)
        db.execute("""CREATE OR REPLACE FUNCTION public.julianday(value TEXT) RETURNS DOUBLE PRECISION
            LANGUAGE sql STABLE AS 'SELECT EXTRACT(EPOCH FROM value::timestamptz)::double precision / 86400.0 + 2440587.5'""")


def connect(target):
    testing = os.environ.get('VIBER_TEST_POSTGRES_URL')
    if testing and not postgres(target):
        schema = 'test_' + hashlib.sha256(str(Path(target).resolve()).encode()).hexdigest()[:20]
        with _lock:
            if schema not in _test_schemas:
                bootstrap(testing, schema)
                if Path(target).is_file():
                    import_sqlite(target, testing, schema)
                _test_schemas.add(schema)
        return PostgresConnection(testing, schema)
    if postgres(target):
        return PostgresConnection(str(target))
    db = sqlite3.connect(target, timeout=30)
    db.row_factory = sqlite3.Row
    return db


def import_sqlite(source, target, schema='public'):
    """Import an offline backup atomically, preserving SQLite row ordering."""
    bootstrap(target, schema)
    report = {}
    with closing(sqlite3.connect(Path(source).resolve().as_uri()+'?mode=ro', uri=True)) as old:
        tables = old.execute("SELECT name,sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").fetchall()
        with closing(PostgresConnection(target, schema)) as new, new:
            for table, ddl in tables:
                if new.execute('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=? AND table_name=?', (schema,table)).fetchone()[0]:
                    raise ValueError('Target is not empty; migration will not overwrite existing data.')
                new.execute(ddl)
                cols = [r[1] for r in old.execute('PRAGMA table_info("'+table+'")')]
                rows = old.execute('SELECT '+','.join('"'+c+'"' for c in cols)+',rowid FROM "'+table+'" ORDER BY rowid').fetchall()
                new.executemany('INSERT INTO '+table+'('+','.join(cols)+',rowid) VALUES('+','.join('?' for _ in range(len(cols)+1))+')', rows)
                count = new.execute('SELECT COUNT(*) FROM '+table).fetchone()[0]
                if count != len(rows):
                    raise ValueError('Migration record count mismatch for '+table)
                report[table] = count
                for column in ('rowid','id'):
                    if column=='id' and column not in cols:
                        continue
                    sequence = new.raw.execute('SELECT pg_get_serial_sequence(%s,%s)', (schema+'.'+table,column)).fetchone()[0]
                    if sequence:
                        maximum = new.raw.execute('SELECT MAX('+column+') FROM '+table).fetchone()[0]
                        new.raw.execute('SELECT setval(%s,%s,%s)', (sequence, maximum or 1, maximum is not None))
    return report
